/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ajedrez.visual.multiplayer;

import ajedrez.code.conection.ConexionJDBC;
import ajedrez.code.conection.DatosConexion;
import ajedrez.code.util.Sound;
import ajedrez.code.util.Util;
import com.sun.java.swing.plaf.windows.WindowsLookAndFeel;
import java.awt.Toolkit;
import java.sql.ResultSet;
import javax.swing.JDialog;
import javax.swing.JFrame;

import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Rene
 */
public class CrearServer extends JDialog {

    /**
     * Creates new form CrearServer
     */
    ConexionJDBC miConexion;

    public CrearServer(JFrame parent, boolean d) {
        super(parent, d);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/ajedrez/images/app_icon.png")));
        initComponents();
        Sound.init();
        setVisible(true);
//        setAlwaysOnTop(true);
        setLocationRelativeTo(null);
        setResizable(false);
    }

    void create() {
        MultiJugador p=Util.multijugador;
        DatosConexion data=p.dc;
        
        if (!host.getText().equals("") && !port.getText().equals("")
                && !user.getText().equals("") && !bd.getText().equals("")) {
            if (Util.validarIP(host.getText())) {
                miConexion = new ConexionJDBC(host.getText(), port.getText(), bd.getText(), user.getText(), pass.getText());

                // conecto con la bd postgres
                if (miConexion.conectarJDBC3()) {

                    try {
                        UIManager.setLookAndFeel(new WindowsLookAndFeel());
                        try {
                            ResultSet rs = miConexion.ejecutarConsulta("DELETE FROM conection");
                            Util.showAdvice(Util.idioma[103], Util.idioma[101]);
                            ResultSet rs1 = miConexion.ejecutarConsulta("INSERT INTO conection (servidor,invitado,mostrar_jug,id,minutos,comenzo,pieza_server) VALUES ('" + data.servidor + "','" + "" + "','" + data.mostrar_jug + "','1','" + data.minutos + "','" + false + "','" + data.index_pieza + "')");
                            p.dispose();
                            dispose();
                            new WaitingRoom(data, miConexion);

                        } catch (Exception e) {
                            Util.showError(Util.idioma[71]);
                            this.dispose();
                        }

                    } catch (UnsupportedLookAndFeelException ex) {
                    }
                } else {
                    Util.showError(miConexion.conectarJDBC1(), Util.idioma[101]);
                }

            } else {
                Util.showError(Util.idioma[95]);
            }
        } else {
            Util.showWarning(Util.idioma[13]);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        port = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        host = new javax.swing.JTextField();
        bd = new javax.swing.JTextField();
        user = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(Util.idioma[69]);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ajedrez/images/CPU1.png"))); // NOI18N
        jButton1.setText(Util.idioma[109]);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, -1, -1));

        port.setText("5432");
        jPanel1.add(port, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 115, 90, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText(Util.idioma[96]);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 13, -1, -1));

        pass.setText("postgres");
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 89, 90, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(Util.idioma[100]);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 117, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(Util.idioma[97]);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 37, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(Util.idioma[98]);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 65, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ajedrez/images/crearServerLOGO.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(Util.idioma[99]);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 91, -1, -1));

        host.setText("localhost");
        host.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                hostKeyPressed(evt);
            }
        });
        jPanel1.add(host, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 11, 90, -1));

        bd.setText("chess");
        jPanel1.add(bd, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 37, 90, -1));

        user.setText("postgres");
        jPanel1.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 63, 90, -1));

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        create();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void hostKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hostKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() != 8 && evt.getKeyCode() != 127) {
            char c = evt.getKeyChar();
            String t = host.getText();
            if (t.length() > 14) {
                host.setText(t.substring(0, 14));
            }
        }
    }//GEN-LAST:event_hostKeyPressed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(CrearServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(CrearServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(CrearServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(CrearServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                CrearServer dialog = new CrearServer(new MultiJugador(),new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bd;
    private javax.swing.JTextField host;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField port;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
