/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ajedrez.visual.game_interface;

import ajedrez.code.util.Util;

/**
 *
 * @author Rene
 */
public class Numeraciones extends javax.swing.JPanel {

    /**
     * Creates new form Numeraciones
     */
    public Numeraciones() {
        initComponents();
        setVisible(true);
        invert();
    }

    public void invert() {
        if (Util.tableroInvertido) {
            NORTH.setVisible(true);
            EAST.setVisible(true);
            WEST.setVisible(false);
            SOUTH.setVisible(false);
        } else {
            NORTH.setVisible(false);
            EAST.setVisible(false);
            WEST.setVisible(true);
            SOUTH.setVisible(true);
        }
        updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NORTH = new javax.swing.JPanel();
        H1 = new javax.swing.JLabel();
        G1 = new javax.swing.JLabel();
        F1 = new javax.swing.JLabel();
        E1 = new javax.swing.JLabel();
        D1 = new javax.swing.JLabel();
        C1 = new javax.swing.JLabel();
        B1 = new javax.swing.JLabel();
        A1 = new javax.swing.JLabel();
        EAST = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        WEST = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        SOUTH = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        A = new javax.swing.JLabel();
        B = new javax.swing.JLabel();
        C = new javax.swing.JLabel();
        D = new javax.swing.JLabel();
        E = new javax.swing.JLabel();
        F = new javax.swing.JLabel();
        G = new javax.swing.JLabel();
        H = new javax.swing.JLabel();
        boardArea = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        NORTH.setLayout(new java.awt.GridLayout(1, 8));

        H1.setFont(new java.awt.Font("Stencil Std", 1, 16)); // NOI18N
        H1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        H1.setText("H");
        NORTH.add(H1);

        G1.setFont(new java.awt.Font("Stencil Std", 1, 16)); // NOI18N
        G1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        G1.setText("G");
        NORTH.add(G1);

        F1.setFont(new java.awt.Font("Stencil Std", 1, 16)); // NOI18N
        F1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        F1.setText("F");
        NORTH.add(F1);

        E1.setFont(new java.awt.Font("Stencil Std", 1, 16)); // NOI18N
        E1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        E1.setText("E");
        NORTH.add(E1);

        D1.setFont(new java.awt.Font("Stencil Std", 1, 16)); // NOI18N
        D1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        D1.setText("D");
        NORTH.add(D1);

        C1.setFont(new java.awt.Font("Stencil Std", 1, 16)); // NOI18N
        C1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        C1.setText("C");
        NORTH.add(C1);

        B1.setFont(new java.awt.Font("Stencil Std", 1, 16)); // NOI18N
        B1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        B1.setText("B");
        NORTH.add(B1);

        A1.setFont(new java.awt.Font("Stencil Std", 1, 16)); // NOI18N
        A1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        A1.setText("A");
        NORTH.add(A1);

        add(NORTH, java.awt.BorderLayout.PAGE_START);

        EAST.setLayout(new java.awt.GridLayout(8, 1));

        jLabel9.setFont(new java.awt.Font("Stencil Std", 1, 16)); // NOI18N
        jLabel9.setText("1");
        EAST.add(jLabel9);

        jLabel10.setFont(new java.awt.Font("Stencil Std", 1, 16)); // NOI18N
        jLabel10.setText("2");
        EAST.add(jLabel10);

        jLabel11.setFont(new java.awt.Font("Stencil Std", 1, 16)); // NOI18N
        jLabel11.setText("3");
        EAST.add(jLabel11);

        jLabel12.setFont(new java.awt.Font("Stencil Std", 1, 16)); // NOI18N
        jLabel12.setText("4");
        EAST.add(jLabel12);

        jLabel13.setFont(new java.awt.Font("Stencil Std", 1, 16)); // NOI18N
        jLabel13.setText("5");
        EAST.add(jLabel13);

        jLabel14.setFont(new java.awt.Font("Stencil Std", 1, 16)); // NOI18N
        jLabel14.setText("6");
        EAST.add(jLabel14);

        jLabel15.setFont(new java.awt.Font("Stencil Std", 1, 16)); // NOI18N
        jLabel15.setText("7");
        EAST.add(jLabel15);

        jLabel16.setFont(new java.awt.Font("Stencil Std", 1, 16)); // NOI18N
        jLabel16.setText("8");
        EAST.add(jLabel16);

        add(EAST, java.awt.BorderLayout.LINE_END);

        WEST.setLayout(new java.awt.GridLayout(8, 1));

        jLabel1.setFont(new java.awt.Font("Stencil Std", 1, 16)); // NOI18N
        jLabel1.setText("8");
        WEST.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Stencil Std", 1, 16)); // NOI18N
        jLabel2.setText("7");
        WEST.add(jLabel2);

        jLabel3.setFont(new java.awt.Font("Stencil Std", 1, 16)); // NOI18N
        jLabel3.setText("6");
        WEST.add(jLabel3);

        jLabel4.setFont(new java.awt.Font("Stencil Std", 1, 16)); // NOI18N
        jLabel4.setText("5");
        WEST.add(jLabel4);

        jLabel5.setFont(new java.awt.Font("Stencil Std", 1, 16)); // NOI18N
        jLabel5.setText("4");
        WEST.add(jLabel5);

        jLabel6.setFont(new java.awt.Font("Stencil Std", 1, 16)); // NOI18N
        jLabel6.setText("3");
        WEST.add(jLabel6);

        jLabel7.setFont(new java.awt.Font("Stencil Std", 1, 16)); // NOI18N
        jLabel7.setText("2");
        WEST.add(jLabel7);

        jLabel8.setFont(new java.awt.Font("Stencil Std", 1, 16)); // NOI18N
        jLabel8.setText("1");
        WEST.add(jLabel8);

        add(WEST, java.awt.BorderLayout.LINE_START);

        SOUTH.setLayout(new java.awt.GridLayout(1, 9));
        SOUTH.add(jLabel17);

        A.setFont(new java.awt.Font("Stencil Std", 1, 16)); // NOI18N
        A.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        A.setText("A");
        SOUTH.add(A);

        B.setFont(new java.awt.Font("Stencil Std", 1, 16)); // NOI18N
        B.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        B.setText("B");
        SOUTH.add(B);

        C.setFont(new java.awt.Font("Stencil Std", 1, 16)); // NOI18N
        C.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        C.setText("C");
        SOUTH.add(C);

        D.setFont(new java.awt.Font("Stencil Std", 1, 16)); // NOI18N
        D.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        D.setText("D");
        SOUTH.add(D);

        E.setFont(new java.awt.Font("Stencil Std", 1, 16)); // NOI18N
        E.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        E.setText("E");
        SOUTH.add(E);

        F.setFont(new java.awt.Font("Stencil Std", 1, 16)); // NOI18N
        F.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        F.setText("F");
        SOUTH.add(F);

        G.setFont(new java.awt.Font("Stencil Std", 1, 16)); // NOI18N
        G.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        G.setText("G");
        SOUTH.add(G);

        H.setFont(new java.awt.Font("Stencil Std", 1, 16)); // NOI18N
        H.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        H.setText("H");
        SOUTH.add(H);

        add(SOUTH, java.awt.BorderLayout.PAGE_END);

        boardArea.setLayout(new java.awt.GridLayout(1, 0));
        add(boardArea, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel A;
    private javax.swing.JLabel A1;
    private javax.swing.JLabel B;
    private javax.swing.JLabel B1;
    private javax.swing.JLabel C;
    private javax.swing.JLabel C1;
    private javax.swing.JLabel D;
    private javax.swing.JLabel D1;
    private javax.swing.JLabel E;
    private javax.swing.JLabel E1;
    private javax.swing.JPanel EAST;
    private javax.swing.JLabel F;
    private javax.swing.JLabel F1;
    private javax.swing.JLabel G;
    private javax.swing.JLabel G1;
    private javax.swing.JLabel H;
    private javax.swing.JLabel H1;
    private javax.swing.JPanel NORTH;
    private javax.swing.JPanel SOUTH;
    private javax.swing.JPanel WEST;
    public javax.swing.JPanel boardArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
